# Generated by Django 6.0.1 on 2026-05-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('issuer', models.CharField(max_length=150)),
                ('year', models.CharField(blank=True, help_text="e.g. '2024'", max_length=50)),
                ('url', models.URLField(blank=True, help_text='Verification link if any', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('school', models.CharField(max_length=150)),
                ('year', models.CharField(help_text="e.g. '2019 - 2025'", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('start_date', models.CharField(help_text="e.g. '2025' or '2019'", max_length=50)),
                ('end_date', models.CharField(default='Present', help_text="e.g. 'Present' or '2024'", max_length=50)),
                ('description', models.TextField(help_text='Provide details, use newlines for bullet points.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(help_text="Comma-separated tech, e.g. 'Python, Django, SQLite'", max_length=255)),
                ('github_url', models.CharField(help_text='GitHub repository link or username/repo', max_length=250)),
                ('live_url', models.URLField(blank=True, help_text='Live website URL', null=True)),
                ('icon_class', models.CharField(default='fas fa-code', help_text='FontAwesome icon for card header', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('web_dev', 'Web Design & Full-Stack Development'), ('digital_mkt', 'Digital Marketing & SEO'), ('design', 'Graphic Design & CMS'), ('soft_skills', 'Soft & Transferable Skills')], default='web_dev', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.IntegerField(default=85, help_text='Skill percentage (e.g. 90 for 90%)')),
                ('icon_class', models.CharField(blank=True, help_text="FontAwesome icon class e.g. 'fab fa-python'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
